version: "3.8"

services:
  postgres:
    build:
      context: ./postgres
    env_file: ./.env
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ./pgadmin
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - 8000:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
  pgadmin:
